# Generated by Django 5.2 on 2025-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experience_years',
            new_name='years_of_experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_for_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(default='Unkown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default='00000000000000000000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('oncology', 'Oncology'), ('gastroenterology', 'Gastroenterology'), ('gynecology', 'Gynecology & Obstetrics'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('anesthesiology', 'Anesthesiology'), ('general_surgery', 'General Surgery'), ('plastic_surgery', 'Plastic Surgery'), ('vascular_surgery', 'Vascular Surgery'), ('rheumatology', 'Rheumatology'), ('infectious_diseases', 'Infectious Diseases'), ('immunology', 'Immunology'), ('hematology', 'Hematology'), ('sports_medicine', 'Sports Medicine'), ('geriatrics', 'Geriatrics'), ('family_medicine', 'Family Medicine'), ('internal_medicine', 'Internal Medicine'), ('pain_management', 'Pain Management'), ('rehabilitation', 'Physical Medicine & Rehabilitation')], max_length=100),
        ),
    ]
