# Generated by Django 5.2 on 2025-05-04 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_experience_years_doctor_years_of_experience_and_more'),
        ('doctors', '0003_doctorprofile_available_for_online_doctorprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_doctor', to='doctors.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referring_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_doctor', to='doctors.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
