# Generated by Django 5.2 on 2025-05-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_available_for_online_doctorprofile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
